version: '3.0'
services:
  # rsa-container:
  #   build:
  #     context: .
  #     dockerfile: rsa.Dockerfile
  #   command: ["tail", "-f", "/dev/null"]
  #   volumes:
  #     - ./data:/data
  #     - "/etc/localtime:/etc/localtime:ro"
  #   networks:
  #     - network_services

  back-service:
    container_name: fast-api-back
    build: 
      context: .
      dockerfile: fast-api-back.Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data:/fast-api/data"
    networks:
      - network_services
    # depends_on:
    #   - rsa-container

networks:
  network_services:
    driver: bridge
